/* Copyright (c) 2026 SECOM CO., LTD. All rights reserved. */
/* SPDX-License-Identifier: BSD-2-Clause */
#ifndef TWEP_WR_TA_H
#define TWEP_WR_TA_H

#define TA_TWEP_WR_UUID \
	{ 0x6b9f4d2a, 0x2f3e, 0x4c7b, \
		{ 0x9d, 0x21, 0x5a, 0x6f, 0x0e, 0x3c, 0x8b, 0x10 } }

#define TA_TWEP_WR_CMD_PING 0
#define TA_TWEP_WR_CMD_GET_PLATFORM_STATUS 1
#define TA_TWEP_WR_CMD_SECURE_STORAGE_PUT 2
#define TA_TWEP_WR_CMD_SECURE_STORAGE_GET 3
#define TA_TWEP_WR_CMD_GET_RANDOM 4
#define TA_TWEP_WR_CMD_GET_TIME 5
#define TA_TWEP_WR_CMD_CBOR_DRY_RUN 6
#define TA_TWEP_WR_CMD_WAMR_SPIKE_EXEC 7
#define TA_TWEP_WR_CMD_INIT 8
#define TA_TWEP_WR_CMD_EXECUTE 9
#define TA_TWEP_WR_CMD_RESUME_HOST_IO 10
#define TA_TWEP_WR_CMD_MEASURE_WASM 11

#ifdef TWEP_TA_D043_TEST_HOOKS
#define TA_TWEP_WR_CMD_D043_TEST 0x80000043

#define TA_TWEP_WR_D043_TEST_RESET 0
#define TA_TWEP_WR_D043_TEST_ARM_FAULT 1
#define TA_TWEP_WR_D043_TEST_WRITE_OBJECT 2
#define TA_TWEP_WR_D043_TEST_DELETE_OBJECT 3
#define TA_TWEP_WR_D043_TEST_GET_GENERATION 4
#define TA_TWEP_WR_D043_TEST_GET_PENDING_STATE 5
#define TA_TWEP_WR_D043_TEST_CATALOG_COMMIT 6
#define TA_TWEP_WR_D043_TEST_CATALOG_EXPECT_ACTIVE 7
#define TA_TWEP_WR_D043_TEST_NONCATALOG_COMMIT 8
#define TA_TWEP_WR_D043_TEST_CATALOG_EXPECT_PRESENT 9

#define TA_TWEP_WR_D043_OBJECT_SLOT0 0
#define TA_TWEP_WR_D043_OBJECT_SLOT1 1
#define TA_TWEP_WR_D043_OBJECT_LEGACY 2
#define TA_TWEP_WR_D043_OBJECT_RESULT 3
#define TA_TWEP_WR_D043_OBJECT_CATALOG_SLOT0 4
#define TA_TWEP_WR_D043_OBJECT_CATALOG_SLOT1 5

#define TA_TWEP_WR_D043_FAULT_NONE 0
#define TA_TWEP_WR_D043_FAULT_CONTINUATION_ALLOC 1
#define TA_TWEP_WR_D043_FAULT_SLOT_CREATE 2
#define TA_TWEP_WR_D043_FAULT_SLOT_WRITE 3
#define TA_TWEP_WR_D043_FAULT_SLOT_AFTER_CLOSE 4
#define TA_TWEP_WR_D043_FAULT_SLOT_REOPEN 5
#define TA_TWEP_WR_D043_FAULT_RESULT_WRITE 6
#define TA_TWEP_WR_D047_FAULT_CATALOG_SLOT_CREATE 7
#define TA_TWEP_WR_D047_FAULT_CATALOG_SLOT_WRITE 8
#define TA_TWEP_WR_D047_FAULT_CATALOG_SLOT_AFTER_CLOSE 9
#define TA_TWEP_WR_D047_FAULT_CATALOG_SLOT_REOPEN 10
#define TA_TWEP_WR_D047_FAULT_CATALOG_SLOT_READBACK 11
#endif

#endif /* TWEP_WR_TA_H */
